// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/risk_engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionId      string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount             float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Merchant           string                 `protobuf:"bytes,4,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Location           string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	UserProfileContext string                 `protobuf:"bytes,6,opt,name=user_profile_context,json=userProfileContext,proto3" json:"user_profile_context,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_api_proto_risk_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_risk_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_risk_engine_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AnalyzeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AnalyzeRequest) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *AnalyzeRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AnalyzeRequest) GetUserProfileContext() string {
	if x != nil {
		return x.UserProfileContext
	}
	return ""
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBlocked     bool                   `protobuf:"varint,1,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AiPushMsg     string                 `protobuf:"bytes,3,opt,name=ai_push_msg,json=aiPushMsg,proto3" json:"ai_push_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_api_proto_risk_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_risk_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_risk_engine_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *AnalyzeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AnalyzeResponse) GetAiPushMsg() string {
	if x != nil {
		return x.AiPushMsg
	}
	return ""
}

var File_api_proto_risk_engine_proto protoreflect.FileDescriptor

const file_api_proto_risk_engine_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/risk_engine.proto\x12\n" +
	"riskengine\"\xd2\x01\n" +
	"\x0eAnalyzeRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bmerchant\x18\x04 \x01(\tR\bmerchant\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x120\n" +
	"\x14user_profile_context\x18\x06 \x01(\tR\x12userProfileContext\"h\n" +
	"\x0fAnalyzeResponse\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x01 \x01(\bR\tisBlocked\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1e\n" +
	"\vai_push_msg\x18\x03 \x01(\tR\taiPushMsg2b\n" +
	"\x11RiskEngineService\x12M\n" +
	"\x12AnalyzeTransaction\x12\x1a.riskengine.AnalyzeRequest\x1a\x1b.riskengine.AnalyzeResponseB-Z+github.com/tokyosplif/ai-risk-engine/pkg/pbb\x06proto3"

var (
	file_api_proto_risk_engine_proto_rawDescOnce sync.Once
	file_api_proto_risk_engine_proto_rawDescData []byte
)

func file_api_proto_risk_engine_proto_rawDescGZIP() []byte {
	file_api_proto_risk_engine_proto_rawDescOnce.Do(func() {
		file_api_proto_risk_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_risk_engine_proto_rawDesc), len(file_api_proto_risk_engine_proto_rawDesc)))
	})
	return file_api_proto_risk_engine_proto_rawDescData
}

var file_api_proto_risk_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_risk_engine_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: riskengine.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 1: riskengine.AnalyzeResponse
}
var file_api_proto_risk_engine_proto_depIdxs = []int32{
	0, // 0: riskengine.RiskEngineService.AnalyzeTransaction:input_type -> riskengine.AnalyzeRequest
	1, // 1: riskengine.RiskEngineService.AnalyzeTransaction:output_type -> riskengine.AnalyzeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_risk_engine_proto_init() }
func file_api_proto_risk_engine_proto_init() {
	if File_api_proto_risk_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_risk_engine_proto_rawDesc), len(file_api_proto_risk_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_risk_engine_proto_goTypes,
		DependencyIndexes: file_api_proto_risk_engine_proto_depIdxs,
		MessageInfos:      file_api_proto_risk_engine_proto_msgTypes,
	}.Build()
	File_api_proto_risk_engine_proto = out.File
	file_api_proto_risk_engine_proto_goTypes = nil
	file_api_proto_risk_engine_proto_depIdxs = nil
}
