// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api/proto/risk_engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskEngineService_AnalyzeTransaction_FullMethodName = "/riskengine.RiskEngineService/AnalyzeTransaction"
)

// RiskEngineServiceClient is the client API for RiskEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskEngineServiceClient interface {
	// Метод для аналізу транзакції
	AnalyzeTransaction(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type riskEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskEngineServiceClient(cc grpc.ClientConnInterface) RiskEngineServiceClient {
	return &riskEngineServiceClient{cc}
}

func (c *riskEngineServiceClient) AnalyzeTransaction(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, RiskEngineService_AnalyzeTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskEngineServiceServer is the server API for RiskEngineService service.
// All implementations must embed UnimplementedRiskEngineServiceServer
// for forward compatibility.
type RiskEngineServiceServer interface {
	// Метод для аналізу транзакції
	AnalyzeTransaction(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedRiskEngineServiceServer()
}

// UnimplementedRiskEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskEngineServiceServer struct{}

func (UnimplementedRiskEngineServiceServer) AnalyzeTransaction(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeTransaction not implemented")
}
func (UnimplementedRiskEngineServiceServer) mustEmbedUnimplementedRiskEngineServiceServer() {}
func (UnimplementedRiskEngineServiceServer) testEmbeddedByValue()                           {}

// UnsafeRiskEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskEngineServiceServer will
// result in compilation errors.
type UnsafeRiskEngineServiceServer interface {
	mustEmbedUnimplementedRiskEngineServiceServer()
}

func RegisterRiskEngineServiceServer(s grpc.ServiceRegistrar, srv RiskEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedRiskEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskEngineService_ServiceDesc, srv)
}

func _RiskEngineService_AnalyzeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskEngineServiceServer).AnalyzeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskEngineService_AnalyzeTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskEngineServiceServer).AnalyzeTransaction(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskEngineService_ServiceDesc is the grpc.ServiceDesc for RiskEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "riskengine.RiskEngineService",
	HandlerType: (*RiskEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeTransaction",
			Handler:    _RiskEngineService_AnalyzeTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/risk_engine.proto",
}
